
CREATE TABLE novinky (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nadpis VARCHAR(255) NOT NULL,
    popis TEXT NOT NULL,
    obrazek VARCHAR(255) NOT NULL,
    datum DATETIME DEFAULT CURRENT_TIMESTAMP
);
